---
title: "creative data"
format: html
editor: visual
---

## Creative Data Visualization Assignment

### Loading in my data

```{r}
library(tidyverse)

raw <- read_csv("C:/Users/edodg/Documents/SchoolDocs25on/Research/Chpt1/wide.csv")

```

```{r}
head(raw)
```

### Wrangle the data 

```{r}
long <- raw |>
  pivot_longer(
    cols = c(Eland, Springbok, Wildebeest, Steenbok, Gemsbok),  
    names_to = "Species",
    values_to = "Detected"
  )
long <- long|>
  select(DateTime, Camera, Species, Detected)
```

```{r}
head(long)
```

### Detection probabilities

```{r}
detection_probs <- long |>
  group_by(Camera, Species) |>
  summarize(
    Detection_Prob = sum(Detected > 0) / n(),
    .groups = "drop"
  )
```

```{r}
head(detection_probs)
```

```{r}
detection_probs
```

```{r}
library(ggplot2)
```

```{r}
head(detection_cp)
```

```{r}
write_csv(
  detection_probs,
  "C:/Users/edodg/Documents/SchoolDocs25on/ADA/creative_data_representation/detection_probs.csv"
)
```

```{r}
detection_probs <- read_csv("detection_probs.csv")
```

### Visualization

```{r}
install.packages("ggimage")
```

```{r}
library(ggimage)
```

```{r}
install.packages("patchwork")
```

```{r}
library(patchwork)
```

```{r}
detection_cp <- detection_probs |>
  group_by(Species) |>
  summarize(
    Detection_Prob = sum(Detection_Prob),
    .groups = "drop"
  ) |>
  mutate(
    Relative_Prob = Detection_Prob / max(Detection_Prob),              
    CP = round(Relative_Prob * 100),                                    
    Image = paste0(tolower(Species), ".png"),
    Descriptor = case_when(
      CP <= 5 ~ "Wimp",
      CP <= 30 ~ "Scrappy",
      CP <= 75 ~ "Schoolyard Bully",
      CP <= 100 ~ "RUN FOR YOUR LIFE"
    )
  )
```

```{r}
head(detection_cp)
```

```{r}
card_list <- map(1:nrow(detection_cp), function(i) {
  sp <- detection_cp[i, ]

  ggplot(sp, aes(x = 1, y = 1)) +
    geom_tile(fill = "#f7f0e8", color = "black", width = 1.6, height = 1.2) +
    
    geom_image(aes(image = Image), size = 0.35, y = 1.15) +
    
    annotate("text", x = 1, y = 0.75, label = sp$Species, size = 7, fontface = "bold") +
    
    annotate("text", x = 1, y = 0.5, label = paste0("CP ", sp$CP), size = 6) +
    annotate("text", x = 1, y = 0.3, label = sp$Descriptor, size = 5, fontface = "italic") +

    geom_rect(aes(xmin = 0.5, xmax = 1.5, ymin = 0.05, ymax = 0.1), fill = "#dddddd") +
geom_rect(aes(xmin = 0.5, xmax = 0.5 + sp$Relative_Prob, ymin = 0.05, ymax = 0.1), fill = "#3c8dbc") +
annotate("text", x = 1, y = 0.13, label = paste0("Rel. Detection: ", round(sp$Relative_Prob, 2)), size = 4.5) +
    theme_void() +
    theme(plot.margin = margin(10, 10, 10, 10))
})
```

```{r}
card_list
```
